# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0003_auto_20160901_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XII_day_ema', models.FloatField(blank=True, null=True)),
                ('XXVI_day_ema', models.FloatField(blank=True, null=True)),
                ('macd_line', models.FloatField(blank=True, null=True)),
                ('signal_line', models.FloatField(blank=True, null=True)),
                ('stock_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StockHistory')),
            ],
        ),
    ]
