# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, verbose_name=b'Symbol')),
                ('isin', models.CharField(max_length=30, verbose_name=b'ISIN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Stock created at')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_date', models.DateField(verbose_name=b'Traded date')),
                ('open', models.FloatField(verbose_name=b'Open price')),
                ('high', models.FloatField(verbose_name=b'High price')),
                ('low', models.FloatField(verbose_name=b'Low price')),
                ('close', models.FloatField(verbose_name=b'Close price')),
                ('last', models.FloatField(verbose_name=b'Last price')),
                ('prev_close', models.FloatField(verbose_name=b'Previous Close price')),
                ('total_traded_qty', models.IntegerField(verbose_name=b'Total Traded quantity')),
                ('total_traded_value', models.FloatField(verbose_name=b'Total Traded value')),
                ('total_trades', models.IntegerField(verbose_name=b'Total Trades')),
                ('deliverables', models.FloatField(blank=True, null=True)),
                ('watch_list', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
    ]
