# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockhistory_is_filtered'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='moneycontrol_link',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=b'MoneyControl.com'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='comments',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
