# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20160901_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ('trade_date',)},
        ),
        migrations.AddField(
            model_name='stock',
            name='moneycontrol_stock_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'Moneycontrol stock id'),
        ),
    ]
