# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20170427_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'BOUGHT'), (2, 'SOLD')], default=1)),
                ('sold_at', models.DateTimeField(db_index=True, null=True, verbose_name='Sold at')),
                ('sold_price', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='is_filtered',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='watch_list',
        ),
        migrations.AddField(
            model_name='stockorder',
            name='stock_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StockHistory', unique=True),
        ),
    ]
